### ISSUE TITLE
Storage and use of chat history to answer questions

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/bionicgpt#28]
Currently, no context or history of chat is used for subsequent questions, hence every questions needs to contain the full context. Can and how would we add the ability to maintain context throughout the chat session.

Example.
> When was the LIfetime learning act 2023 enacted?
# RESPONSE

> Which act did it amend?

**Comment by ianpurton** [comment]
Use `https://platform.openai.com/docs/guides/gpt/chat-completions-api`

- [ ] The user should be able to set the max number of items to add to the history
- [ ] The "system" entry should contain any context 
- [ ] Find a way to measure tokens used.
- [ ] Restrict history to meet token count
