### ISSUE TITLE
Latest version (3/10) not working

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/bionicgpt#47]
Tried a query with out loading up any datasets and chat returns error, cannot see any error thrown on the backend.

Added a largish file and the deleted it before it had processed
Added a dataset, very small. It was stuck in processing. Never changed status.
 Looked at backend 5 minutes later and it looks to be processing some flarge ile 

fine-tuna-barricade-1       | [2023-10-03T17:22:36Z INFO  actix_web::middleware::logger] 172.21.0.4 "GET /app/team/doc_status/3 HTTP/1.1" 200 0 "-" "-" 0.000807
fine-tuna-barricade-1       | [2023-10-03T17:22:36Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 413.872µs
fine-tuna-embeddings-job-1  | 2023-10-03T17:22:38.913998Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:22:38.914602Z  INFO embeddings_job: Processing embedding id 39
fine-tuna-embeddings-job-1  | 2023-10-03T17:22:50.747231Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:22:50.747865Z  INFO embeddings_job: Processing embedding id 40
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:03.201833Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:03.202704Z  INFO embeddings_job: Processing embedding id 41
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:15.077959Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:15.078916Z  INFO embeddings_job: Processing embedding id 42
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:27.573897Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:27.574657Z  INFO embeddings_job: Processing embedding id 43
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:39.289973Z  INFO open_api: Processing 384 bytes
fine-tuna-embeddings-job-1  | 2023-10-03T17:23:39.290602Z  INFO embeddings_job: Processing embedding id 44

![Screenshot from 2023-10-03 18-19-08](https://github.com/purton-tech/bionicgpt/assets/4700433/80c69a4f-a37b-4199-b0a8-7cf742f357cb)
![Screenshot from 2023-10-03 18-19-43](https://github.com/purton-tech/bionicgpt/assets/4700433/0a03b67d-b6bd-4c49-8762-fb242eb64399)

**Comment by ianpurton** [comment]
Fixed in 0.1.3
