### ISSUE TITLE
Llama2 broken

### ISSUE THREAD

**Issue by arthur-x88** [purton-tech/bionicgpt#61]
comdockerdevenvironmentscode-app-1             | 2023-10-11T12:08:19.262865Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error sending request for url (http://local-ai:8080/v1/embeddings): error trying to connect: dns error: failed to lookup address information: Try again"

**Comment by ianpurton** [comment]
@arthur-x88 Are you using the docker-compose.yml or the devcontainer?

**Comment by arthur-x88** [comment]
Both

**Comment by ianpurton** [comment]
@arthur-x88 This should be fixed in the latest realese.
