### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by kulbinderdio** [purton-tech/bionicgpt#66]
Deployed with latest config file.
Deploys and runs ok, allows me to create user and upload a document, create a prompt

When asked a question, takes a very long time and then returns 'Error occurred while generating'
Backend shows
dev-barricade-1       |
dev-barricade-1       | [2023-10-18T21:52:01Z INFO  actix_web::middleware::logger] 172.18.0.4 "GET /app/team/2/teams_popup HTTP/1.1" 200 0 "-" "-" 0.001444
dev-barricade-1       | [2023-10-18T21:52:01Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 391.193µs
dev-barricade-1       | [2023-10-18T21:52:01Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 2.973ms
dev-app-1             | 2023-10-18T21:52:26.065883Z  INFO open_api: Processing 384 bytes
dev-app-1             | 2023-10-18T21:52:26.069197Z  INFO axum_server::prompt: About to call
dev-app-1             | 2023-10-18T21:52:26.073883Z  INFO axum_server::prompt: Retrieved 1 chunks
dev-app-1             | 2023-10-18T21:52:26.075891Z  INFO axum_server::prompt: Retrieved 0 history items
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:45753: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:44263: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:35263: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:40867: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:40097: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36629: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:45451: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36365: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:46289: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:46299: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39867: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:41493: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:46165: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:38533: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:45215: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:39897: connect: connection refused"
dev-local-ai-1        | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:33209: connect: connection refused"
dev-db-1              | 2023-10-18 21:54:07.857 UTC [76] LOG:  checkpoint starting: time
dev-db-1              | 2023-10-18 21:54:10.123 UTC [76] LOG:  checkpoint complete: wrote 23 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.215 s, sync=0.020 s, total=2.267 s; sync files=19, longest=0.011 s, average=0.002 s; distance=6 kB, estimate=1094 kB

**Comment by ianpurton** [comment]
LLM integrations are now here https://github.com/bionic-gpt/doc-llama
